# ===============================
# Oracle Database Config
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=system
spring.datasource.password=sarasu10

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SQL Initialization
# ===============================
spring.sql.init.mode=always
spring.sql.init.platform=oracle
spring.sql.init.data-locations=classpath:data.sql

# Run data.sql AFTER JPA starts
spring.jpa.defer-datasource-initialization=true