INSERT INTO customer (customer_id, name, contact, email, status)
VALUES (1055, 'Eidiko', '1234657890', 'eidiko@gmail.com', 'ACTIVE');

INSERT INTO VENDOR (VENDOR_ID, ADDRESS1, ADDRESS2, CITY, CONTACT, COUNTRY, EMAIL, NAME, PINCODE, STATE, STATUS)
VALUES (1001, '123 Main Street', 'Suite 400', 'Bangalore', '9876543210', 'India', 'vendor@example.com', 'ABC Technologies', '560001', 'Karnataka', 'ACTIVE');

INSERT ALL
  INTO PRODUCT (PRICE, QUANTITY, STATUS, CREATED_AT, PRODUCT_ID, UPDATED_AT, VENDOR_ID, NAME)
  VALUES (1999.99, 50, 'ACTIVE', SYSTIMESTAMP, 2001, SYSTIMESTAMP, 1001, 'Laptop')
  INTO PRODUCT (PRICE, QUANTITY, STATUS, CREATED_AT, PRODUCT_ID, UPDATED_AT, VENDOR_ID, NAME)
  VALUES (499.50, 120, 'ACTIVE', SYSTIMESTAMP, 2002, SYSTIMESTAMP, 1001, 'Wireless Mouse')
SELECT 1 FROM DUAL;


